import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import QueryClientWrapper from "@/components/ui/query-client-wrapper";
import { UserContextProvider } from "@/context/user-context";
import React from "react";
import AuthSession from "@/app/_component/auth-session";
import Header from "@/components/ui/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "넷 뿌려졌스",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserContextProvider>
          <QueryClientWrapper>
            <Header />
            {/*<AuthSession>*/}
            {children}
            {/*</AuthSession>*/}
          </QueryClientWrapper>
        </UserContextProvider>
      </body>
    </html>
  );
}
